/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as BroadcastRouteImport } from './routes/broadcast'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as QuotationsRouteImport } from './routes/quotations'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RfqRouteImport } from './routes/rfq'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SupportRouteImport } from './routes/support'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminServiceProvidersRouteImport } from './routes/admin.service-providers'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminBookingsBookingIdRouteImport } from './routes/admin.bookings.$bookingId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const BroadcastRoute = BroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationsRoute = QuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RfqRoute = RfqRouteImport.update({
  id: '/rfq',
  path: '/rfq',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServiceProvidersRoute = AdminServiceProvidersRouteImport.update({
  id: '/admin/service-providers',
  path: '/admin/service-providers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookingsBookingIdRoute = AdminBookingsBookingIdRouteImport.update({
  id: '/admin/bookings/$bookingId',
  path: '/admin/bookings/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/awards': typeof AwardsRoute
  '/broadcast': typeof BroadcastRoute
  '/companies': typeof CompaniesRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/projects': typeof ProjectsRoute
  '/quotations': typeof QuotationsRoute
  '/reports': typeof ReportsRoute
  '/rfq': typeof RfqRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/service-providers': typeof AdminServiceProvidersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/bookings/$bookingId': typeof AdminBookingsBookingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/awards': typeof AwardsRoute
  '/broadcast': typeof BroadcastRoute
  '/companies': typeof CompaniesRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/projects': typeof ProjectsRoute
  '/quotations': typeof QuotationsRoute
  '/reports': typeof ReportsRoute
  '/rfq': typeof RfqRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/service-providers': typeof AdminServiceProvidersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/bookings/$bookingId': typeof AdminBookingsBookingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/awards': typeof AwardsRoute
  '/broadcast': typeof BroadcastRoute
  '/companies': typeof CompaniesRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/projects': typeof ProjectsRoute
  '/quotations': typeof QuotationsRoute
  '/reports': typeof ReportsRoute
  '/rfq': typeof RfqRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/service-providers': typeof AdminServiceProvidersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/bookings/$bookingId': typeof AdminBookingsBookingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/awards'
    | '/broadcast'
    | '/companies'
    | '/login'
    | '/payments'
    | '/projects'
    | '/quotations'
    | '/reports'
    | '/rfq'
    | '/settings'
    | '/support'
    | '/admin/categories'
    | '/admin/service-providers'
    | '/admin/users'
    | '/admin/bookings/$bookingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/awards'
    | '/broadcast'
    | '/companies'
    | '/login'
    | '/payments'
    | '/projects'
    | '/quotations'
    | '/reports'
    | '/rfq'
    | '/settings'
    | '/support'
    | '/admin/categories'
    | '/admin/service-providers'
    | '/admin/users'
    | '/admin/bookings/$bookingId'
  id:
    | '__root__'
    | '/'
    | '/awards'
    | '/broadcast'
    | '/companies'
    | '/login'
    | '/payments'
    | '/projects'
    | '/quotations'
    | '/reports'
    | '/rfq'
    | '/settings'
    | '/support'
    | '/admin/categories'
    | '/admin/service-providers'
    | '/admin/users'
    | '/admin/bookings/$bookingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AwardsRoute: typeof AwardsRoute
  BroadcastRoute: typeof BroadcastRoute
  CompaniesRoute: typeof CompaniesRoute
  LoginRoute: typeof LoginRoute
  PaymentsRoute: typeof PaymentsRoute
  ProjectsRoute: typeof ProjectsRoute
  QuotationsRoute: typeof QuotationsRoute
  ReportsRoute: typeof ReportsRoute
  RfqRoute: typeof RfqRoute
  SettingsRoute: typeof SettingsRoute
  SupportRoute: typeof SupportRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminServiceProvidersRoute: typeof AdminServiceProvidersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminBookingsBookingIdRoute: typeof AdminBookingsBookingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broadcast': {
      id: '/broadcast'
      path: '/broadcast'
      fullPath: '/broadcast'
      preLoaderRoute: typeof BroadcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotations': {
      id: '/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof QuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfq': {
      id: '/rfq'
      path: '/rfq'
      fullPath: '/rfq'
      preLoaderRoute: typeof RfqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/service-providers': {
      id: '/admin/service-providers'
      path: '/admin/service-providers'
      fullPath: '/admin/service-providers'
      preLoaderRoute: typeof AdminServiceProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bookings/$bookingId': {
      id: '/admin/bookings/$bookingId'
      path: '/admin/bookings/$bookingId'
      fullPath: '/admin/bookings/$bookingId'
      preLoaderRoute: typeof AdminBookingsBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AwardsRoute: AwardsRoute,
  BroadcastRoute: BroadcastRoute,
  CompaniesRoute: CompaniesRoute,
  LoginRoute: LoginRoute,
  PaymentsRoute: PaymentsRoute,
  ProjectsRoute: ProjectsRoute,
  QuotationsRoute: QuotationsRoute,
  ReportsRoute: ReportsRoute,
  RfqRoute: RfqRoute,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminServiceProvidersRoute: AdminServiceProvidersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminBookingsBookingIdRoute: AdminBookingsBookingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
